### ISSUE TITLE
Vault unit is in error state when vault service is sealed

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/vault-k8s-operator#12]
**Describe the bug**
Deploy vault and another charm and relate them. Vault unit went into error state.
Expected vault to be in Blocked state.

**To Reproduce**
1. Deploy vault charm and any charm that requires tls_interface_certificate library
2. Relate both the charms
3. Verify juju status. vault unit is in error state

**Expected behavior**
Vault unit should be in Blocked state.

**Logs**
```
unit-vault-0: 09:14:45 ERROR unit.vault/0.juju-log certificates:3: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 242, in <module>
    main(VaultCharm)
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-vault-0/charm/lib/charms/tls_certificates_interface/v1/tls_certificates.py", line 969, in _on_relation_changed
    self.on.certificate_creation_request.emit(
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 80, in _on_certificate_creation_request
    certificate = self.vault.issue_certificate(
  File "/var/lib/juju/agents/unit-vault-0/charm/src/vault.py", line 269, in issue_certificate
    return self._issue_certificate(**config)
  File "/var/lib/juju/agents/unit-vault-0/charm/src/vault.py", line 278, in _issue_certificate
    response = self._client.write(
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/hvac/v1/__init__.py", line 264, in write
    return self._adapter.post(f"/v1/{path}", json=kwargs, wrap_ttl=wrap_ttl)
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/hvac/adapters.py", line 125, in post
    return self.request("post", url, **kwargs)
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/hvac/adapters.py", line 356, in request
    response = super().request(*args, **kwargs)
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/hvac/adapters.py", line 322, in request
    utils.raise_for_error(
  File "/var/lib/juju/agents/unit-vault-0/charm/venv/hvac/utils.py", line 58, in raise_for_error
    raise exceptions.VaultDown(message, errors=errors, method=method, url=url)
hvac.exceptions.VaultDown: Vault is sealed, on post http://localhost:8200/v1/charm-pki-local/sign/local
```

**Environment**
 - Vault version: latest/edge
 - Juju version: 3.0/edge
 - Cloud Environment juju+microk8s
 - Kubernetes version 1.25

**Additional context**
Needs a check if Vault is ready or not here [1] and defer the event if vault is not ready.
Also need to catch ``hvac.exceptions.VaultDown, hvac.exceptions.Forbidden`` exceptions in Is_ready function [2]

I tried to implement this but one caveat is the deferred event is not triggered until next hook is triggered ( in this case update-status)
Any ideas to trigger the event sooner?

[1] https://github.com/canonical/vault-k8s-operator/blob/main/src/charm.py#L80
[2] https://github.com/canonical/vault-k8s-operator/blob/main/src/vault.py#L58-L71

**Comment by gruyaume** [comment]
This issue is fixed. Now Vault automatically initialises and unseals.
