### ISSUE TITLE
OSError on Vault PKI relation created event

### ISSUE THREAD

**Issue by gruyaume** [canonical/vault-k8s-operator#311]
#### Describe the bug
OSError on Vault PKI relation created event.

#### To Reproduce
Follow the [How-to Use Vault as an intermediate CA ](https://charmhub.io/vault-k8s/docs/h-use-vault-as-intermediate-ca) guide:
1. `juju deploy vault-k8s --channel=1.15/edge --trust`
2. `juju config vault common_name=mydomain.com`
3. `juju deploy self-signed-certificates`
4. `juju integrate vault:tls-certificates-pki self-signed-certificates`
5. `juju deploy tls-certificates-requirer --config common_name=demo.mydomain.com`
6. `juju integrate tls-certificates-requirer vault:vault-pki`

#### Expected behavior
No error

#### Logs

```
Model  Controller          Cloud/Region        Version  SLA          Timestamp
lev    microk8s-localhost  microk8s/localhost  3.4.0    unsupported  07:34:01-04:00

App                        Version  Status   Scale  Charm                      Channel    Rev  Address         Exposed  Message
self-signed-certificates            active       1  self-signed-certificates   stable      72  10.152.183.79   no       
tls-certificates-requirer           active       1  tls-certificates-requirer  stable      59  10.152.183.148  no       Certificate request is sent
vault-k8s                           waiting      1  vault-k8s                  1.15/edge  201  10.152.183.250  no       installing agent

Unit                          Workload  Agent  Address      Ports  Message
self-signed-certificates/0*   active    idle   10.1.182.51         
tls-certificates-requirer/0*  active    idle   10.1.182.38         Certificate request is sent
vault-k8s/0*                  error     idle   10.1.182.15         hook failed: "vault-pki-relation-created"
```

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/./src/charm.py", line 1355, in <module>
    main(VaultCharm)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/main.py", line 511, in _emit
    ops.charm._evaluate_status(self.charm)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/charm.py", line 1228, in _evaluate_status
    charm.on.collect_unit_status.emit()
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/framework.py", line 352, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/framework.py", line 851, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/framework.py", line 941, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/./src/charm.py", line 212, in _on_collect_status
    if not vault.is_api_available():
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/lib/charms/vault_k8s/v0/vault_client.py", line 128, in is_api_available
    self._client.sys.read_health_status(standby_ok=True)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/hvac/api/system_backend/health.py", line 68, in read_health_status
    return self._adapter.head(
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/hvac/adapters.py", line 211, in head
    return self.request("head", url, **kwargs)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/hvac/adapters.py", line 408, in request
    response = super().request(*args, **kwargs)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/hvac/adapters.py", line 367, in request
    response = self.session.request(
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/requests/adapters.py", line 458, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/requests/adapters.py", line 261, in cert_verify
    raise OSError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /var/lib/juju/storage/certs/0/ca.pem
```
#### Environment

- Charm / library version (if relevant):1.15/edge (rev. 201)
- Juju version (output from `juju --version`): 3.4.0
- Cloud Environment: MicroK8s
- Kubernetes version (output from `kubectl version --short`): 1.29-strict/stable

#### Other information

I was not able to reproduce the same error on the Vault machine charm

**Comment by Kayra1** [comment]
This usually happens when the certs storage is not attached to the unit yet. I'm taking a look.
