### ISSUE TITLE
ModelError: ERROR cannot access secret

### ISSUE THREAD

**Issue by DanielArndt** [canonical/vault-k8s-operator#414]
### Bug Description

https://github.com/canonical/vault-k8s-operator/actions/runs/9519849182/job/26244305237

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/./src/charm.py", line 280, in <module>
    main(TLSRequirerCharm)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/framework.py", line 352, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/framework.py", line 851, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/framework.py", line 941, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/./src/charm.py", line 244, in _on_get_certificate_action
    if self._certificate_is_stored:
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/./src/charm.py", line [221](https://github.com/canonical/vault-k8s-operator/actions/runs/9519849182/job/26244305237#step:9:222), in _certificate_is_stored
    return self._secret_exists(label=self._get_certificate_secret_label())
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/./src/charm.py", line 233, in _secret_exists
    self.model.get_secret(label=label)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/model.py", line 280, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/model.py", line 3370, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-tls-certificates-requirer-0/charm/venv/ops/model.py", line 3024, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR cannot access "cpm800ljtp7c7b4q4lig-1"
```

### To Reproduce

Unknown

### Environment

Integration tests: https://github.com/canonical/vault-k8s-operator/actions/runs/9519849182

### Relevant log output

```shell
Log output attached
```

### Additional context

As the error suggests, it appears that charm doesn't have access to the secret. I need to do a bit more investigation because I wasn't able to figure out how this happens by looking at the charm and integration tests. The secret appears to be solely owned by the caller, so a call to `secret.grant()` shouldn't be necessary. I'm also not sure if this is the same error that is normally returned when asking for a secret we don't have access to... seems odd that it would crash the charm, so I'll need to do a bit more digging here.

I'm not quite positive how to move forward here, but I'll do some more digging.

[debug_log.txt](https://github.com/user-attachments/files/16084357/debug_log.txt)

**Comment by DanielArndt** [comment]
Unfortunately, I can't see anything glaringly wrong here. Either there is a race condition, or this happened during the teardown when something has failed. The tests tear down the model and break a lot of things when something fails, and removing secrets while they're still expected to be there is definitely one thing I've seen it do.

Unfortunately, I haven't been able to discover why it might have failed in the first place. 

Without more information, I feel like this isn't worth spending too much more time on. We should re-open if we see this happen again, though.
