### ISSUE TITLE
hvac.exceptions.InvalidRequest: source address unauthorized through CIDR restrictions on the secret ID

### ISSUE THREAD

**Issue by kelkawi-a** [canonical/vault-k8s-operator#437]
### Bug Description

We have a relation between the `vault-k8s` and `temporal-worker-k8s` charms on the `vault-kv` interface. The logic we are introducing in [this PR](https://github.com/canonical/temporal-worker-k8s-operator/pull/22) is for the Temporal worker charm to read secrets from Vault on config changes. Refreshing the `temporal-worker-k8s` charm while in development leads to an error state with the below logs from the output. I've added the portion for updating the Vault relation binding to the `update_status` hook, but it's worth noting that I see the below in the logs:

```
unit-temporal-worker-k8s-0: 08:29:49 WARNING unit.temporal-worker-k8s/0.juju-log failed to update vault relation - AttributeError("'UpdateStatusEvent' object has no attribute 'relation'")
```

### To Reproduce

The steps are a bit involved as it requires setting up a Temporal server. I'd be happy to have a quick chat about this.
1. Setup Temporal server ecosystem
2. Deploy and initialize vault-k8s charm
3. git clone git@github.com:canonical/temporal-worker-k8s-operator.git
4. git checkout worker-secrets
5. cd temporal-worker-k8s-operator
6. make -C resource_sample_py build_rock
7. charmcraft pack && juju deploy ./temporal-worker-k8s_ubuntu-22.04-amd64.charm --resource temporal-worker-image=localhost:32000/temporal-worker-rock
8. juju config temporal-worker-k8s host="temporal-k8s:7233" namespace="default" queue="test-queue"
9. Create the below `secrets.yaml` file:

```yaml
secrets:
  vault:
    - path: my-secrets
      key: key1
```

10. juju config temporal-worker-k8s secrets=@path/to/secrets.yaml
11. juju relate temporal-worker-k8s vault-k8s
12. charmcraft pack && juju refresh --path="./temporal-worker-k8s_ubuntu-22.04
-amd64.charm" temporal-worker-k8s --force-units --resource temporal-worker-image=localhost:32000/tempo
ral-worker-rock

### Environment

Operating system: Ubuntu 22.04.4 LTS

Juju CLI: 3.5.2-genericlinux-amd64

Juju agent: 3.5.2

Charm revision: 256

microk8s: v1.25.16

### Relevant log output

```shell
unit-temporal-worker-k8s-0: 23:53:59 ERROR unit.temporal-worker-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 541, in <module>
    main.main(TemporalWorkerK8SOperatorCharm)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/main.py", line 513, in _emit
    self.framework.reemit()
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/framework.py", line 870, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/src/log.py", line 41, in decorated
    return method(self, event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 175, in _on_config_changed
    self._update(event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 407, in _update
    charm_config_env = self.create_env()
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 300, in create_env
    vault_client = self._get_vault_client(vault_config)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 322, in _get_vault_client
    return VaultClient(
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/src/vault_client.py", line 33, in __init__
    self._authenticate(role_id, role_secret_id)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/src/vault_client.py", line 45, in _authenticate
    self.client.auth.approle.login(
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/hvac/api/auth_methods/approle.py", line 506, in login
    return self._adapter.login(
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/hvac/adapters.py", line 230, in login
    response = self.post(url, **kwargs)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/hvac/adapters.py", line 159, in post
    return self.request("post", url, **kwargs)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/hvac/adapters.py", line 408, in request
    response = super().request(*args, **kwargs)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/hvac/adapters.py", line 376, in request
    self._raise_for_error(method, url, response)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/hvac/adapters.py", line 294, in _raise_for_error
    utils.raise_for_error(
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/hvac/utils.py", line 41, in raise_for_error
    raise exceptions.VaultError.from_status(
hvac.exceptions.InvalidRequest: source address "10.1.232.49" unauthorized through CIDR restrictions on the secret ID, on post https://10.152.183.53:8200/v1/auth/approle/login
```

**Comment by gruyaume** [comment]
Hello @kian99 thank you for opening this issue. We should be looking at it in the next couple of days. Thank you.

**Comment by kayra1** [comment]
Hello @kelkawi-a, I had some time today to recreate the issue you've been having.

Some context first:
When a Vault KV relation is created, the Requirer unit library creates a request that includes the binding address of the unit. Once Vault receives a KV request, it will create an Approle specifically for that unit, and use the given IP as the CIDR restriction. This IP is the only IP that can communicate directly with Vault. When you refresh a charm, the IP changes, but this does not rerun any of the relation joined logic.

Since Vault can't read the IP address of the relation, it expects you to provide it again in the databag, so that it can reissue credentials.

A config changed runs when the charm is refreshed, and you correctly request credentials from Vault [here](https://github.com/canonical/temporal-worker-k8s-operator/blob/e75f82a64deb6aa84029e27d350681fa2780df22/src/charm.py#L306) in your PR.

The critical issue is the fact that you're attempting to access the `event.relation` value of a `config-changed` event, which does not point to the relation between the unit and KV. In this case, you'd want to manually find the KV relation by running something like 
```python
self.model.get_relation(relation_name="vault")
```

Please try this and let me know if this solves your problem.

**Comment by kelkawi-a** [comment]
Thanks for investigating! That indeed seems to have been the issue. You may want to update the `vault_kv` library [here](https://github.com/canonical/vault-k8s-operator/blob/main/lib/charms/vault_k8s/v0/vault_kv.py#L98) to reflect this.

**Comment by kayra1** [comment]
that's a good point :D
