### ISSUE TITLE
PeerSecretError when deploying charm with Juju 3.2.3

### ISSUE THREAD

**Issue by gruyaume** [canonical/vault-k8s-operator#71]
#### Describe the bug

PeerSecretError when deploying charm with Juju 3.2.3

#### To Reproduce

```bash
sudo snap install juju --channel=3.2/stable
juju bootstrap microk8s
juju add-model dev
juju deploy vault-k8s --channel=edge --trust -n 3
```

#### Expected behavior
No error

#### Logs

```
guillaume@thinkpad:~$ juju status
Model  Controller          Cloud/Region        Version  SLA          Timestamp
dev    microk8s-localhost  microk8s/localhost  3.2.3    unsupported  10:35:46-05:00

App                Version  Status   Scale  Charm              Channel  Rev  Address         Exposed  Message
vault-k8s                   waiting      3  vault-k8s          edge      45  10.152.183.200  no       installing agent

Unit                  Workload  Agent  Address      Ports  Message
vault-k8s/0*          error     idle   10.1.19.187         hook failed: "vault-peers-relation-created"
vault-k8s/1           waiting   idle   10.1.19.173         Waiting for other units to provide their addresses
vault-k8s/2           waiting   idle   10.1.19.134         Waiting for other units to provide their addresses
```

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/model.py", line 2946, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-vault-k8s-0/secret-get', '--label', 'vault-initialization', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/model.py", line 3302, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/model.py", line 2948, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR consumer label "vault-initialization" not found


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/./src/charm.py", line 735, in _get_initialization_secret_from_peer_relation
    juju_secret = self.model.get_secret(label=VAULT_INITIALIZATION_SECRET_LABEL)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/model.py", line 276, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/model.py", line 3305, in secret_get
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/./src/charm.py", line 901, in <module>
    main(VaultCharm)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/framework.py", line 340, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/framework.py", line 842, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/./src/charm.py", line 321, in _configure
    root_token, unseal_keys = self._get_initialization_secret_from_peer_relation()
  File "/var/lib/juju/agents/unit-vault-k8s-0/charm/./src/charm.py", line 739, in _get_initialization_secret_from_peer_relation
    raise PeerSecretError(secret_name=VAULT_INITIALIZATION_SECRET_LABEL)
PeerSecretError: Could not retrieve secret from peer relation
```

#### Environment

- Charm version: edge (rev. 45)
- Juju version: 3.2.3
- Cloud Environment: MicroK8s
- Kubernetes version: v1.27.7

**Comment by saltiyazan** [comment]
[Bug](https://bugs.launchpad.net/juju/+bug/2043961) in Juju reported, a fix there should fix this bug.

**Comment by saltiyazan** [comment]
There won't be anymore releases for Juju 3.2. That version of Juju is now EOL. This won't be fixed in Juju.
